###
# Spring settings
###
spring:
  #Database settings
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/receipts_checking_bot_app_db
    username: postgres
    password: postgres
  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

#Telegram bot settings
bot:
  name: FiscalReceiptsCheckingBot
  token: 6168758085:AAGCYSwaw2aRrfAO9CF904XK166sQNOL41c
