spring:
  #Database settings
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: testUsername
    password: testPassword


  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  #Flyway settings
  flyway:
    enabled: false