###
# Spring settings
###
spring:
  #Database settings
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/receipts_checking_bot_app_db
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
  #Jpa settings
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false

#Telegram bot settings
bot:
  name: FiscalReceiptsCheckingBot
  token: 6168758085:AAGCYSwaw2aRrfAO9CF904XK166sQNOL41c
