package ua.bizbiz.receiptscheckingbot.persistance.entity;

public enum ChatStatus {
    ENTERING_SECRET_CODE,
    AUTHORIZED_AS_USER,
    AUTHORIZED_AS_ADMIN,
    CREATING_USER,
    READING_USER,
    UPDATING_USER,
    DELETING_USER,
    GETTING_REPORT,
    ADMIN_GETTING_PROMOTIONS,
    ADMIN_GETTING_USERS,
    CREATING_PROMOTION,
    UPDATING_PROMOTION,
    DELETING_PROMOTION,
    SENDING_ANNOUNCEMENT,
    SENDING_ANNOUNCEMENT_TO_ALL,
    SENDING_ANNOUNCEMENT_TO_PERSON,
    USER_GETTING_PROMOTIONS,
    SENDING_RECEIPT,
    SENDING_RECEIPT_PHOTO,
    CHECKING_RECEIPTS,
}
